name = "ArDCA_PPI_sampler"
uuid = "8599883a-6c2a-42a6-acd1-c8a27c9b47c5"  # Generate a real UUID
authors = ["Carlos Gandarilla-Perez <carlosgandarilla88@gmail.com>", "Lisa Gennai <lisa.gennai@epfl.ch>", "Martin Weigt <martin.weigt@gmail.com>"]
version = "0.1.0"
